// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK9A9om07R7lecbfXdzX4b5V5JTBUfzng',
    appId: '1:1058586227189:android:e8aa5e62f8348b9bbcb0bc',
    messagingSenderId: '1058586227189',
    projectId: 'insuguia-f26e3',
    storageBucket: 'insuguia-f26e3.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxlLlTR3M3UIQwhmK8kkPi8ML3M86xh3Q',
    appId: '1:1058586227189:web:638e98a916a302f8bcb0bc',
    messagingSenderId: '1058586227189',
    projectId: 'insuguia-f26e3',
    authDomain: 'insuguia-f26e3.firebaseapp.com',
    storageBucket: 'insuguia-f26e3.firebasestorage.app',
    measurementId: 'G-BRB2P6ZCGF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSfM1S5vB1V4RfTL1en1UPE-_-CyYN0Nk',
    appId: '1:1058586227189:ios:c9e29b3c1777928fbcb0bc',
    messagingSenderId: '1058586227189',
    projectId: 'insuguia-f26e3',
    storageBucket: 'insuguia-f26e3.firebasestorage.app',
    iosBundleId: 'com.example.flutterLayoutApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSfM1S5vB1V4RfTL1en1UPE-_-CyYN0Nk',
    appId: '1:1058586227189:ios:c9e29b3c1777928fbcb0bc',
    messagingSenderId: '1058586227189',
    projectId: 'insuguia-f26e3',
    storageBucket: 'insuguia-f26e3.firebasestorage.app',
    iosBundleId: 'com.example.flutterLayoutApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxlLlTR3M3UIQwhmK8kkPi8ML3M86xh3Q',
    appId: '1:1058586227189:web:eaf1fa65f6c1a32cbcb0bc',
    messagingSenderId: '1058586227189',
    projectId: 'insuguia-f26e3',
    authDomain: 'insuguia-f26e3.firebaseapp.com',
    storageBucket: 'insuguia-f26e3.firebasestorage.app',
    measurementId: 'G-1QRKYBRFLH',
  );

}